default:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: airflow
      password: airflow
      port: 5433  # Match the exposed port in docker-compose
      dbname: stockdb
      schema: test
  target: dev