FROM apache/airflow:3.0.6

# Step 1: Switch to root to install system dependencies
USER root

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libpq-dev \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Step 2: Switch back to airflow before installing Python packages
USER airflow

COPY ../../requirements.txt /requirements.txt

RUN pip install --no-cache-dir -r /requirements.txt